[2023-01-30T16:12:19.282+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.308+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.310+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.314+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:12:19.316+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.338+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-30 16:12:17.205977+00:00
[2023-01-30T16:12:19.373+0000] {standard_task_runner.py:55} INFO - Started process 3966 to run task
[2023-01-30T16:12:19.391+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-30T16:12:17.205977+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0jrasqg5']
[2023-01-30T16:12:19.407+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask is_api_available
[2023-01-30T16:12:19.593+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:12:17.205977+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:12:19.704+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:12:17.205977+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:12:17.205977+00:00
[2023-01-30T16:12:19.706+0000] {http.py:120} INFO - Poking: api/
[2023-01-30T16:12:19.716+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-30T16:12:19.719+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-30T16:12:20.014+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-30T16:12:20.023+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230130T161217, start_date=20230130T161219, end_date=20230130T161220
[2023-01-30T16:12:20.059+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:12:20.075+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
