[2023-01-30T16:12:19.257+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.273+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-30T16:12:17.205977+00:00 [queued]>
[2023-01-30T16:12:19.274+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.275+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:12:19.277+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:12:19.300+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-30 16:12:17.205977+00:00
[2023-01-30T16:12:19.321+0000] {standard_task_runner.py:55} INFO - Started process 3965 to run task
[2023-01-30T16:12:19.363+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-01-30T16:12:17.205977+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpv2mu182u']
[2023-01-30T16:12:19.371+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask create_table
[2023-01-30T16:12:19.568+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2023-01-30T16:12:17.205977+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:12:19.667+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:12:17.205977+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:12:17.205977+00:00
[2023-01-30T16:12:19.681+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-01-30T16:12:19.688+0000] {sql.py:315} INFO - Running statement: 
        create table if not exists users(
            firstname text not null, 
            lastname text not null, 
            country text not null, 
            username text not null, 
            password text not null,
            email text not null);
            , parameters: None
[2023-01-30T16:12:19.691+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-01-30T16:12:19.703+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230130T161217, start_date=20230130T161219, end_date=20230130T161219
[2023-01-30T16:12:19.745+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:12:19.781+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
