[2023-01-30T16:20:35.592+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-30T16:20:34.670538+00:00 [queued]>
[2023-01-30T16:20:35.600+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-01-30T16:20:34.670538+00:00 [queued]>
[2023-01-30T16:20:35.601+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:20:35.602+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:20:35.602+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:20:35.610+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-01-30 16:20:34.670538+00:00
[2023-01-30T16:20:35.616+0000] {standard_task_runner.py:55} INFO - Started process 4389 to run task
[2023-01-30T16:20:35.620+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-01-30T16:20:34.670538+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpaez4uwr7']
[2023-01-30T16:20:35.622+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask create_table
[2023-01-30T16:20:35.663+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2023-01-30T16:20:34.670538+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:20:35.702+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:20:34.670538+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:20:34.670538+00:00
[2023-01-30T16:20:35.709+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-01-30T16:20:35.712+0000] {sql.py:315} INFO - Running statement: 
        create table if not exists users(
            firstname text not null, 
            lastname text not null, 
            country text not null, 
            username text not null, 
            password text not null,
            email text not null);
            , parameters: None
[2023-01-30T16:20:35.714+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-01-30T16:20:35.720+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230130T162034, start_date=20230130T162035, end_date=20230130T162035
[2023-01-30T16:20:35.752+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:20:35.771+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
