[2023-01-30T16:08:13.243+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:08:11.350676+00:00 [queued]>
[2023-01-30T16:08:13.263+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:08:11.350676+00:00 [queued]>
[2023-01-30T16:08:13.264+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:08:13.265+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-30T16:08:13.267+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T16:08:13.285+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-01-30 16:08:11.350676+00:00
[2023-01-30T16:08:13.295+0000] {standard_task_runner.py:55} INFO - Started process 3713 to run task
[2023-01-30T16:08:13.304+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-01-30T16:08:11.350676+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp6b0wf60g']
[2023-01-30T16:08:13.307+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask is_api_available
[2023-01-30T16:08:13.428+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-01-30T16:08:11.350676+00:00 [running]> on host 3c28126f9714
[2023-01-30T16:08:13.541+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-01-30T16:08:11.350676+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-30T16:08:11.350676+00:00
[2023-01-30T16:08:13.543+0000] {http.py:120} INFO - Poking: api/
[2023-01-30T16:08:13.557+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-01-30T16:08:13.560+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-01-30T16:08:13.892+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-01-30T16:08:13.902+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230130T160811, start_date=20230130T160813, end_date=20230130T160813
[2023-01-30T16:08:13.967+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-30T16:08:13.994+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
